[config]
default_to_workspace = false

[env]
IMAP__PORT = "3993"
SMTP__PORT = "3025"
GREENMAIL__HOST = "127.0.0.1"
IMAP__HOST = "127.0.0.1"
GREENMAIL__API_PORT = "8020"

[tasks.build]
description = "Build binaries"
command = "cargo"
args = ["build", "--workspace", "--all-features"]

[tasks.clippy]
description = "Runs clippy."
clear = true
command = "cargo"
args = [
  "clippy",
  "--all-targets",
  "--all-features",
  "--workspace",
  "--",
  "-D",
  "warnings",
  "-W",
  "clippy::dbg_macro",
]

[tasks.fmt-check]
description = "Runs the cargo rustfmt plugin during CI."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.deny-check]
description = "Runs the cargo deny plugin during CI."
command = "cargo"
args = ["deny", "check"]

[tasks.test]
description = "Runs tests."
clear = true
run_task = { name = [
  "doc-tests",
  "nextest",
], fork = true, cleanup_task = "test-cleanup" }
dependencies = ["greenmail-test-user"]

[tasks.test-cleanup]
description = "Cleanup tasks after tests."
run_task = { name = ["greenmail-purge"], parallel = true }

[tasks.nextest]
description = "Runs tests without dependencies."
command = "cargo"
args = ["nextest", "run", "--no-fail-fast", "${@}"]

[tasks.doc-tests]
description = "Run doc tests"
command = "cargo"
args = ["test", "--doc"]

[tasks.greenmail-purge]
description = "Purge greenmail"
script = """
curl -X POST http://${GREENMAIL__HOST}:${GREENMAIL__API_PORT}/api/service/reset 
"""

[tasks.greenmail-test-user]
description = "Create a test user in greenmail"
script = """
curl -X POST http://${GREENMAIL__HOST}:${GREENMAIL__API_PORT}/api/user \
    -H "Content-Type: application/json" \
    --data '{"login": "test", "password": "test", "email": "test@email.com"}'
"""
